name: data-to-json

# 1) 이 블록을 최상단에 추가
permissions:
  contents: write

on:
  push:
    paths:
      - "data_raw.txt"

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # 기본 GITHUB_TOKEN 에 쓰기 권한을 유지
          persist-credentials: true  

      - name: Convert data_raw.txt to data.json
        run: |
          cat > convert.py << 'PYCODE'
          import json
          result = {"users": []}
          with open("data_raw.txt", "r", encoding="utf-8") as f:
              for line in f:
                  line = line.strip()
                  if not line:
                      continue
                  tokens = [t.strip() for t in line.split(",")]
                  if len(tokens) < 4:
                      continue
                  name, combo, account, shares = tokens[:4]
                  try:
                      sharesOwned = int(shares)
                  except:
                      continue
                  result["users"].append({
                      "name": name,
                      "combo": combo,
                      "account": account,
                      "stockPrice": 66300,
                      "sharesOwned": sharesOwned
                  })
          with open("data.json", "w", encoding="utf-8") as f:
              json.dump(result, f, ensure_ascii=False, indent=4)
          python3 convert.py
      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git diff --quiet || git commit -m "chore: auto-convert data_raw.txt → data.json"
          git push
